name: "Test"
on:
  push:
    branches: [ .*,master,test_actions,test_workflow1 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Send Request 1"
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: ${{ secrets.TOKEN }}
        reviewers: "nimble-robotics"
